### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by OKNoah** [vasanthk/react-inline-edit#1]
Consider adding a demo so people can see exactly how it behaves.

**Comment by vasanthk** [comment]
:+1: 
Been a lil busy of-late.. I'll definitely add a demo soon.

**Comment by patrickgordon** [comment]
Would also like to see a demo

**Comment by wdmtech** [comment]
Me too :+1:

**Comment by vasanthk** [comment]
@OKNoah @patrickgordon @wdmtech Sorry guys, It's been a while since I worked on this and when I look at my code now - I certainly see scope for cleanup. I am hoping to work on this sometime in the coming weeks and add in some unit tests/demo as well. I'll let you guys know when I push it out :)

**Comment by sassanh** [comment]
:+1:

**Comment by vasanthk** [comment]
@sassanh @wdmtech @patrickgordon @OKNoah 
Really sorry for the delay!
I have pushed out a new version with a simpler API + Demo as well. 
Try it out when you get the chance to and let me know your thoughts/ideas/ramblings :)
Thanks and wish you all a Happy New Year 2016 :)
