### ISSUE TITLE
contentEditable?

### ISSUE THREAD

**Issue by OKNoah** [vasanthk/react-inline-edit#2]
```
// in order to render the updated text,
// you need to pass it as a prop to contentEditable.
// This gives you increased flexibility.
```

Can you elaborate on this part? Currently I am able to edit the text on the page, but it doesn't update the state in the React component. 

```
onChange: function ( text ) {
    this.setState( { text: text } )
},
```

**Comment by CoreyTrombley** [comment]
Hey @OKNoah checkout [This](http://blog.benmcmahen.com/post/109613882545/enable-inline-editing-with-react) and [this also](https://github.com/bmcmahen/react-wysiwyg)

**Comment by vasanthk** [comment]
Yup, I highly recommend @bmcmahen 's [react-wysiwyg](https://github.com/bmcmahen/react-wysiwyg) It's well maintained.
I wrote this module as a learning experience and did some tweaks to suit my project needs.
