### ISSUE TITLE
InlineEdit is an empty object

### ISSUE THREAD

**Issue by rhythnic** [vasanthk/react-inline-edit#23]
I'm having trouble using 2.0.  When I import react-inline-edit, it is an empty object.

```
const InlineEdit = require('react-inline-edit');
console.log(InlineEdit);
// {}
```

**Comment by vasanthk** [comment]
@rhythnic I see.. Does the demo work fine for you?

**Comment by vasanthk** [comment]
@rhythnic The issue was with the dist folder having a bad copy. Updated the script. Should work fine now.
