### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'deepestAncestor.firstChild')

### ISSUE THREAD

**Issue by OKNoah** [vasanthk/react-inline-edit#3]
I see this error in my console log whenever there is a change event in the editable field. The `onChange` event doesn't seem to file at all. Here is my code.

```
render: function () {
    return (
        <div>
            <InlineEdit 
                /*...*/
                onChange={ this.onChange }
                /*...*/
        </div>
    )
},

/*...*/

onChange: function ( text ) {
    console.log( text )
    this.setState( { text: text } )
}
```

This is actually when using ng-react with Angular. I'll try make another version without to see if it's related to that.

**Comment by vasanthk** [comment]
I highly recommend @bmcmahen 's [react-wysiwyg](https://github.com/bmcmahen/react-wysiwyg) It's well maintained.
I wrote this module as a learning experience and did some tweaks to suit my project needs.
